import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Janella Vanilla",
  description: "Generated by her royal highness, Janella - the Vanilla Queen. Bow down to her majesty.",
};

export default function RootLayout({ children }) {

    let header = (
        <header>
            <Link href="/">
              <h1>{metadata.title}</h1>
            </Link>
        </header>
    );

    let footer = (
        <footer>
            <p>© {new Date().getFullYear()} Janella Codes🤤💕</p>
        </footer>
    );
  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
